version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: servaretur/lab4:compose-app
    container_name: app
    networks:
      - public
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: servaretur/lab4:compose-monitoring
    container_name: monitoring
    network_mode: host
      
networks:
  public:
    driver: bridge
